# Generated by Django 3.0.7 on 2020-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
